# Generated by Django 6.0.1 on 2026-01-12 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(help_text='pdf | docx | text | url | manual', max_length=50)),
                ('source_name', models.CharField(help_text='Filename, URL, or user-defined name', max_length=255)),
                ('raw_text', models.TextField(help_text='Original extracted text (pre-chunking)')),
                ('checksum', models.CharField(help_text='SHA-256 hash for deduplication', max_length=64)),
                ('ingestion_status', models.CharField(choices=[('PENDING', 'Pending'), ('INGESTED', 'Ingested'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
