# Generated by Django 5.2.10 on 2026-01-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='document',
            name='raw_text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='ingestion_status',
            field=models.CharField(choices=[('INGESTED', 'Ingested'), ('FAILED', 'Failed')], default='INGESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_name',
            field=models.CharField(help_text='Filename or user-defined document name', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(help_text='pdf | text', max_length=20),
        ),
    ]
